# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import character_sync_pb2 as character__sync__pb2


class CharacterSyncStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.UpdateCharacterWorldStates = channel.unary_unary(
        '/CharacterSync/UpdateCharacterWorldStates',
        request_serializer=character__sync__pb2.CharacterWorldStates.SerializeToString,
        response_deserializer=character__sync__pb2.UpdateCharacterWorldStateResult.FromString,
        )
    self.GetCharacterWorldStates = channel.unary_unary(
        '/CharacterSync/GetCharacterWorldStates',
        request_serializer=character__sync__pb2.CharacterWorldStateRequest.SerializeToString,
        response_deserializer=character__sync__pb2.CharacterWorldStates.FromString,
        )
    self.UpdatePersonalWorldState = channel.unary_unary(
        '/CharacterSync/UpdatePersonalWorldState',
        request_serializer=character__sync__pb2.CharacterWorldStateUpdate.SerializeToString,
        response_deserializer=character__sync__pb2.UpdatePersonalWorldStateResult.FromString,
        )
    self.GetPlayerWorldStates = channel.unary_unary(
        '/CharacterSync/GetPlayerWorldStates',
        request_serializer=character__sync__pb2.CharacterWorldStateRequest.SerializeToString,
        response_deserializer=character__sync__pb2.CharacterWorldStates.FromString,
        )


class CharacterSyncServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def UpdateCharacterWorldStates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCharacterWorldStates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdatePersonalWorldState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPlayerWorldStates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CharacterSyncServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'UpdateCharacterWorldStates': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateCharacterWorldStates,
          request_deserializer=character__sync__pb2.CharacterWorldStates.FromString,
          response_serializer=character__sync__pb2.UpdateCharacterWorldStateResult.SerializeToString,
      ),
      'GetCharacterWorldStates': grpc.unary_unary_rpc_method_handler(
          servicer.GetCharacterWorldStates,
          request_deserializer=character__sync__pb2.CharacterWorldStateRequest.FromString,
          response_serializer=character__sync__pb2.CharacterWorldStates.SerializeToString,
      ),
      'UpdatePersonalWorldState': grpc.unary_unary_rpc_method_handler(
          servicer.UpdatePersonalWorldState,
          request_deserializer=character__sync__pb2.CharacterWorldStateUpdate.FromString,
          response_serializer=character__sync__pb2.UpdatePersonalWorldStateResult.SerializeToString,
      ),
      'GetPlayerWorldStates': grpc.unary_unary_rpc_method_handler(
          servicer.GetPlayerWorldStates,
          request_deserializer=character__sync__pb2.CharacterWorldStateRequest.FromString,
          response_serializer=character__sync__pb2.CharacterWorldStates.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CharacterSync', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
