# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import login_pb2 as login__pb2


class LoginStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUserToken = channel.unary_unary(
        '/Login/GetUserToken',
        request_serializer=login__pb2.UserTokenRequest.SerializeToString,
        response_deserializer=login__pb2.UserToken.FromString,
        )
    self.Logout = channel.unary_unary(
        '/Login/Logout',
        request_serializer=login__pb2.UserToken.SerializeToString,
        response_deserializer=login__pb2.LogoutResult.FromString,
        )


class LoginServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUserToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Logout(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LoginServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUserToken': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserToken,
          request_deserializer=login__pb2.UserTokenRequest.FromString,
          response_serializer=login__pb2.UserToken.SerializeToString,
      ),
      'Logout': grpc.unary_unary_rpc_method_handler(
          servicer.Logout,
          request_deserializer=login__pb2.UserToken.FromString,
          response_serializer=login__pb2.LogoutResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Login', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
