# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='login.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0blogin.proto\" \n\x10UserTokenRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\tUserToken\x12\r\n\x05token\x18\x01 \x01(\t\"\x0e\n\x0cLogoutResult2_\n\x05Login\x12/\n\x0cGetUserToken\x12\x11.UserTokenRequest\x1a\n.UserToken\"\x00\x12%\n\x06Logout\x12\n.UserToken\x1a\r.LogoutResult\"\x00\x62\x06proto3')
)




_USERTOKENREQUEST = _descriptor.Descriptor(
  name='UserTokenRequest',
  full_name='UserTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='UserTokenRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=47,
)


_USERTOKEN = _descriptor.Descriptor(
  name='UserToken',
  full_name='UserToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='UserToken.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=75,
)


_LOGOUTRESULT = _descriptor.Descriptor(
  name='LogoutResult',
  full_name='LogoutResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['UserTokenRequest'] = _USERTOKENREQUEST
DESCRIPTOR.message_types_by_name['UserToken'] = _USERTOKEN
DESCRIPTOR.message_types_by_name['LogoutResult'] = _LOGOUTRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserTokenRequest = _reflection.GeneratedProtocolMessageType('UserTokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERTOKENREQUEST,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:UserTokenRequest)
  })
_sym_db.RegisterMessage(UserTokenRequest)

UserToken = _reflection.GeneratedProtocolMessageType('UserToken', (_message.Message,), {
  'DESCRIPTOR' : _USERTOKEN,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:UserToken)
  })
_sym_db.RegisterMessage(UserToken)

LogoutResult = _reflection.GeneratedProtocolMessageType('LogoutResult', (_message.Message,), {
  'DESCRIPTOR' : _LOGOUTRESULT,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:LogoutResult)
  })
_sym_db.RegisterMessage(LogoutResult)



_LOGIN = _descriptor.ServiceDescriptor(
  name='Login',
  full_name='Login',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=93,
  serialized_end=188,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUserToken',
    full_name='Login.GetUserToken',
    index=0,
    containing_service=None,
    input_type=_USERTOKENREQUEST,
    output_type=_USERTOKEN,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Logout',
    full_name='Login.Logout',
    index=1,
    containing_service=None,
    input_type=_USERTOKEN,
    output_type=_LOGOUTRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOGIN)

DESCRIPTOR.services_by_name['Login'] = _LOGIN

# @@protoc_insertion_point(module_scope)
