# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import matchmaker_pb2 as matchmaker__pb2


class MatchMakerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateGame = channel.unary_unary(
        '/MatchMaker/CreateGame',
        request_serializer=matchmaker__pb2.GameCreationRequest.SerializeToString,
        response_deserializer=matchmaker__pb2.GameCreationResult.FromString,
        )
    self.GetActiveGames = channel.unary_unary(
        '/MatchMaker/GetActiveGames',
        request_serializer=matchmaker__pb2.GetActiveGamesRequest.SerializeToString,
        response_deserializer=matchmaker__pb2.GameList.FromString,
        )
    self.ConnectToGame = channel.unary_unary(
        '/MatchMaker/ConnectToGame',
        request_serializer=matchmaker__pb2.GameConnectionRequest.SerializeToString,
        response_deserializer=matchmaker__pb2.GameConnectionResult.FromString,
        )
    self.DisconnectFromGame = channel.unary_unary(
        '/MatchMaker/DisconnectFromGame',
        request_serializer=matchmaker__pb2.GameDisconnectionRequest.SerializeToString,
        response_deserializer=matchmaker__pb2.GameDisconnectionResult.FromString,
        )


class MatchMakerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateGame(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetActiveGames(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConnectToGame(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DisconnectFromGame(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MatchMakerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateGame': grpc.unary_unary_rpc_method_handler(
          servicer.CreateGame,
          request_deserializer=matchmaker__pb2.GameCreationRequest.FromString,
          response_serializer=matchmaker__pb2.GameCreationResult.SerializeToString,
      ),
      'GetActiveGames': grpc.unary_unary_rpc_method_handler(
          servicer.GetActiveGames,
          request_deserializer=matchmaker__pb2.GetActiveGamesRequest.FromString,
          response_serializer=matchmaker__pb2.GameList.SerializeToString,
      ),
      'ConnectToGame': grpc.unary_unary_rpc_method_handler(
          servicer.ConnectToGame,
          request_deserializer=matchmaker__pb2.GameConnectionRequest.FromString,
          response_serializer=matchmaker__pb2.GameConnectionResult.SerializeToString,
      ),
      'DisconnectFromGame': grpc.unary_unary_rpc_method_handler(
          servicer.DisconnectFromGame,
          request_deserializer=matchmaker__pb2.GameDisconnectionRequest.FromString,
          response_serializer=matchmaker__pb2.GameDisconnectionResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MatchMaker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
