# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matchmaker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='matchmaker.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10matchmaker.proto\"7\n\x13GameCreationRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\tgame_name\x18\x02 \x01(\t\"]\n\x12GameCreationResult\x12\x1b\n\x13\x63reation_successful\x18\x01 \x01(\x08\x12*\n\x10game_description\x18\x02 \x01(\x0b\x32\x10.GameDescription\"\x17\n\x15GetActiveGamesRequest\"5\n\x0fGameDescription\x12\x11\n\tgame_name\x18\x01 \x01(\t\x12\x0f\n\x07game_id\x18\x02 \x01(\t\"+\n\x08GameList\x12\x1f\n\x05games\x18\x01 \x03(\x0b\x32\x10.GameDescription\"<\n\x15GameConnectionRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x12\n\nuser_token\x18\x02 \x01(\t\"5\n\x14GameConnectionResult\x12\x1d\n\x15\x63onnection_successful\x18\x01 \x01(\x08\".\n\x18GameDisconnectionRequest\x12\x12\n\nuser_token\x18\x01 \x01(\t\"\x19\n\x17GameDisconnectionResult2\x8d\x02\n\nMatchMaker\x12\x39\n\nCreateGame\x12\x14.GameCreationRequest\x1a\x13.GameCreationResult\"\x00\x12\x35\n\x0eGetActiveGames\x12\x16.GetActiveGamesRequest\x1a\t.GameList\"\x00\x12@\n\rConnectToGame\x12\x16.GameConnectionRequest\x1a\x15.GameConnectionResult\"\x00\x12K\n\x12\x44isconnectFromGame\x12\x19.GameDisconnectionRequest\x1a\x18.GameDisconnectionResult\"\x00\x62\x06proto3')
)




_GAMECREATIONREQUEST = _descriptor.Descriptor(
  name='GameCreationRequest',
  full_name='GameCreationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='GameCreationRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_name', full_name='GameCreationRequest.game_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=75,
)


_GAMECREATIONRESULT = _descriptor.Descriptor(
  name='GameCreationResult',
  full_name='GameCreationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='creation_successful', full_name='GameCreationResult.creation_successful', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_description', full_name='GameCreationResult.game_description', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=170,
)


_GETACTIVEGAMESREQUEST = _descriptor.Descriptor(
  name='GetActiveGamesRequest',
  full_name='GetActiveGamesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=195,
)


_GAMEDESCRIPTION = _descriptor.Descriptor(
  name='GameDescription',
  full_name='GameDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_name', full_name='GameDescription.game_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_id', full_name='GameDescription.game_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=250,
)


_GAMELIST = _descriptor.Descriptor(
  name='GameList',
  full_name='GameList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='games', full_name='GameList.games', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=295,
)


_GAMECONNECTIONREQUEST = _descriptor.Descriptor(
  name='GameConnectionRequest',
  full_name='GameConnectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_id', full_name='GameConnectionRequest.game_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_token', full_name='GameConnectionRequest.user_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=357,
)


_GAMECONNECTIONRESULT = _descriptor.Descriptor(
  name='GameConnectionResult',
  full_name='GameConnectionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connection_successful', full_name='GameConnectionResult.connection_successful', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=412,
)


_GAMEDISCONNECTIONREQUEST = _descriptor.Descriptor(
  name='GameDisconnectionRequest',
  full_name='GameDisconnectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_token', full_name='GameDisconnectionRequest.user_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=460,
)


_GAMEDISCONNECTIONRESULT = _descriptor.Descriptor(
  name='GameDisconnectionResult',
  full_name='GameDisconnectionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=487,
)

_GAMECREATIONRESULT.fields_by_name['game_description'].message_type = _GAMEDESCRIPTION
_GAMELIST.fields_by_name['games'].message_type = _GAMEDESCRIPTION
DESCRIPTOR.message_types_by_name['GameCreationRequest'] = _GAMECREATIONREQUEST
DESCRIPTOR.message_types_by_name['GameCreationResult'] = _GAMECREATIONRESULT
DESCRIPTOR.message_types_by_name['GetActiveGamesRequest'] = _GETACTIVEGAMESREQUEST
DESCRIPTOR.message_types_by_name['GameDescription'] = _GAMEDESCRIPTION
DESCRIPTOR.message_types_by_name['GameList'] = _GAMELIST
DESCRIPTOR.message_types_by_name['GameConnectionRequest'] = _GAMECONNECTIONREQUEST
DESCRIPTOR.message_types_by_name['GameConnectionResult'] = _GAMECONNECTIONRESULT
DESCRIPTOR.message_types_by_name['GameDisconnectionRequest'] = _GAMEDISCONNECTIONREQUEST
DESCRIPTOR.message_types_by_name['GameDisconnectionResult'] = _GAMEDISCONNECTIONRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameCreationRequest = _reflection.GeneratedProtocolMessageType('GameCreationRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMECREATIONREQUEST,
  '__module__' : 'matchmaker_pb2'
  # @@protoc_insertion_point(class_scope:GameCreationRequest)
  })
_sym_db.RegisterMessage(GameCreationRequest)

GameCreationResult = _reflection.GeneratedProtocolMessageType('GameCreationResult', (_message.Message,), {
  'DESCRIPTOR' : _GAMECREATIONRESULT,
  '__module__' : 'matchmaker_pb2'
  # @@protoc_insertion_point(class_scope:GameCreationResult)
  })
_sym_db.RegisterMessage(GameCreationResult)

GetActiveGamesRequest = _reflection.GeneratedProtocolMessageType('GetActiveGamesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETACTIVEGAMESREQUEST,
  '__module__' : 'matchmaker_pb2'
  # @@protoc_insertion_point(class_scope:GetActiveGamesRequest)
  })
_sym_db.RegisterMessage(GetActiveGamesRequest)

GameDescription = _reflection.GeneratedProtocolMessageType('GameDescription', (_message.Message,), {
  'DESCRIPTOR' : _GAMEDESCRIPTION,
  '__module__' : 'matchmaker_pb2'
  # @@protoc_insertion_point(class_scope:GameDescription)
  })
_sym_db.RegisterMessage(GameDescription)

GameList = _reflection.GeneratedProtocolMessageType('GameList', (_message.Message,), {
  'DESCRIPTOR' : _GAMELIST,
  '__module__' : 'matchmaker_pb2'
  # @@protoc_insertion_point(class_scope:GameList)
  })
_sym_db.RegisterMessage(GameList)

GameConnectionRequest = _reflection.GeneratedProtocolMessageType('GameConnectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMECONNECTIONREQUEST,
  '__module__' : 'matchmaker_pb2'
  # @@protoc_insertion_point(class_scope:GameConnectionRequest)
  })
_sym_db.RegisterMessage(GameConnectionRequest)

GameConnectionResult = _reflection.GeneratedProtocolMessageType('GameConnectionResult', (_message.Message,), {
  'DESCRIPTOR' : _GAMECONNECTIONRESULT,
  '__module__' : 'matchmaker_pb2'
  # @@protoc_insertion_point(class_scope:GameConnectionResult)
  })
_sym_db.RegisterMessage(GameConnectionResult)

GameDisconnectionRequest = _reflection.GeneratedProtocolMessageType('GameDisconnectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMEDISCONNECTIONREQUEST,
  '__module__' : 'matchmaker_pb2'
  # @@protoc_insertion_point(class_scope:GameDisconnectionRequest)
  })
_sym_db.RegisterMessage(GameDisconnectionRequest)

GameDisconnectionResult = _reflection.GeneratedProtocolMessageType('GameDisconnectionResult', (_message.Message,), {
  'DESCRIPTOR' : _GAMEDISCONNECTIONRESULT,
  '__module__' : 'matchmaker_pb2'
  # @@protoc_insertion_point(class_scope:GameDisconnectionResult)
  })
_sym_db.RegisterMessage(GameDisconnectionResult)



_MATCHMAKER = _descriptor.ServiceDescriptor(
  name='MatchMaker',
  full_name='MatchMaker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=490,
  serialized_end=759,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateGame',
    full_name='MatchMaker.CreateGame',
    index=0,
    containing_service=None,
    input_type=_GAMECREATIONREQUEST,
    output_type=_GAMECREATIONRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetActiveGames',
    full_name='MatchMaker.GetActiveGames',
    index=1,
    containing_service=None,
    input_type=_GETACTIVEGAMESREQUEST,
    output_type=_GAMELIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ConnectToGame',
    full_name='MatchMaker.ConnectToGame',
    index=2,
    containing_service=None,
    input_type=_GAMECONNECTIONREQUEST,
    output_type=_GAMECONNECTIONRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DisconnectFromGame',
    full_name='MatchMaker.DisconnectFromGame',
    index=3,
    containing_service=None,
    input_type=_GAMEDISCONNECTIONREQUEST,
    output_type=_GAMEDISCONNECTIONRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATCHMAKER)

DESCRIPTOR.services_by_name['MatchMaker'] = _MATCHMAKER

# @@protoc_insertion_point(module_scope)
